/**
 * Google
 * You are given two strings, s and t which only consist of lowercase letters. 
 * t is generated by shuffling the letters in s as well as potentially adding an additional random character.
 * Return the letter that was randomly added to t if it exists, otherwise, return ' '.
 * Note: You may assume that at most one additional character can be added to t.
 */

#include<iostream>
#include<vector>
using namespace std;

/**
 * @author keshav kabra
 * @since May 29, 2021
 */


/** function findTheDifference
 * @param string, denoting string s
 * @param string, denoting string t
 * @return char, denoting extra character added to t (if any)
 */ 
char findTheDifference(string s, string t)
{
    
    /** Logic :
     * Since s and t consists of only lowercase alphabetic letters,
     * we create a vector of size 26 and initialized by 0.
     * Now, for every character in string s, we increase the count of
     * that location (in vector - acting as map) by 1.
     * For every character in string t, we decrease the count of that 
     * location by 1.
     * 
     * Now, if any position in vector after these operations have a non-zero
     * value, return the corresponding character.
     * If all values are zero, return ' '.
     */ 
    
	vector<int> v(26, 0);
        
    for(char ch : t)
        v[ch-'a']++;
    
    for(char ch : s)
        v[ch-'a']--;
    
    for(int i=0;i<26;i++)
    {
        if(v[i] != 0)
            return i+'a';
    }
    return ' ';
}



// main function - driver code
int main()
{
	
	// TESTCASES
	
	cout<<findTheDifference("foobar", "barfoot")<<"\n";
	cout<<findTheDifference("ide", "idea")<<"\n";
	cout<<findTheDifference("coding", "ingcod")<<"\n";
	
	return 0;
}
